version: "3"

services:
  app:
    image: golang:1.13.5-alpine3.10
    volumes:
      - .:/root/sqlx-lab:cached
      - ./.local/packages:/go/pkg:cached
    working_dir: /root/sqlx-lab
    depends_on:
      - db
    command: >
      go run main.go
    ports:
     - "8000:8000"

  db: &db
    image: mysql:5.7.25
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "5306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:cached
      - ./db/conf.d:/etc/mysql/conf.d:cached
      - ./.local/db/log:/var/log/mysql/mysqld.log:cached
      - ./.local/db/mysql:/var/lib/mysql:cached
