version: "3"

services:
  app:
    image: golang:1.13.5-alpine3.10
    volumes:
      - .:/go/src/github.com/NasSilverBullet/sqlx-lab:cached
      - ./.local/packages:/go/pkg:cached
    depends_on:
      - db
    command: sh -c "go run /go/src/github.com/NasSilverBullet/sqlx-lab/main.go"

  db: &db
    image: mysql:5.7.25
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "5306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:cached
      - ./db/conf.d:/etc/mysql/conf.d:cached
      - ./.local/db/log:/var/log/mysql/mysqld.log:cached
      - ./.local/db/mysql:/var/lib/mysql:cached
